### ISSUE TITLE
Top Nav

### ISSUE THREAD

**Issue by murtosl** [murtosl/HistoryOfFlash_4662W#8]
"On some pages [the navigation] makes the top a little busy, and I’m tempted to think it might work better on the side." 

It ain't going on the side, but I disliked my navigation ever since I expanded to more than four sections and my titles got long. I need to decide what to do. My solution on mobile is also unacceptable. Maybe I should just hamburger menu the whole thing.

**Comment by lingeringcode** [comment]
Yep, you could 'hamburger' it completely, or save that version for the mobile version with an adaptive media query. Up to a certain width, you could apply something akin to Wikipedia's absolute side-panel: 

![selection_104](https://cloud.githubusercontent.com/assets/1388382/11015487/5721ea96-8526-11e5-970d-e90e0a9883b4.png)

This works well for large amounts of content, and you already have some wiggle room on each side to use up. With the media query, you can use the 'display: none' to hide the nav panel on the side to replace it with styles for the hamburger menu.

**Comment by murtosl** [comment]
I used the script here to do it, but I modified that thing a fair bit to get it to work http://www.scriptiny.com/2008/05/horizontal-javascript-accordion-menu/

I can't say it's the smoothest navigation in history, but I'm calling it good.

**Comment by murtosl** [comment]
..The flashing when you mouse over The Future... link is driving me crazy, but I don't even know if that's fixable. By the time the text swaps directions and the plug-in recalculates, I think the flash is unavoidable. I'm lucky the plug-in is smart enough to recalculate. 

It's because the text is trying to go on two lines, and then the plug-in adjusts to one line.
